### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#10]
Some ideas for web user interface.

Of course, the beautiful http://mybinder.org/ is good stating point for inspiration.

Currently, when you enter an address you get redirected to the 'launch' page and then, once the container is started, to the document itself (inside the container). It may be better instead to keep this a single page app and, instead of redirecting, give links to the user.

An advantage of not redirecting is that we can provide info on this page about the container that has been launched (e.g timeout, resource usage) that is not available in the document UI (which doesn't "know" that it is running in a container).

Wireframe:

![page](https://user-images.githubusercontent.com/1152336/26906453-71f4627a-4c41-11e7-9207-0ae6a52b0f2d.png)

**Comment by yoshuawuyts** [comment]
From https://github.com/stencila/sibyl/issues/28

- [ ] Travis fails because of linting errors in shell (but not on my local?) - I'll fix those.

- [ ] On the open notebook link, please add a tilde ie. /~ . This tells the sever running in the container to open the 'main' document in the home directory of the container. The main document will be main.*, index.* or README.* where * is html, md etc

- [ ] Please change naming from "notebooks" to "documents". We're trying to move away from the idea of simple notebooks to fully reproducible documents (with all the layout aspects of a document etc). Also, we'll be using sibyl to "launch" our spreadsheets and possibly other "office suite" document. So documents is better.

- [ ] The large black console feels too "nerdy" - I was thinking that it could be minimised to a single line, or reduced to an icon (that flashes on each line?), and only expands on a user click when they want to see more details.

- [ ] Can you remove "Sibyl Run interactive notebooks in the browser" from the top for now

- [ ] We should link to the docs at https://sibyl.surge.sh somewhere (I'm working on those!)
