### ISSUE TITLE
Routing to bundle containers

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#12]
Once a bundle container has been launched we need to route requests from the browser to the correct container via the single (?) cluster ingress.

Previously we have used Nginx's [X-Accel-Redirect](http://wiki.nginx.org/X-accel) to proxy to R/Python sessions: 
https://github.com/stencila/hub/blob/master/director/nginx.conf#L146

If we used a similar approach `server.js` would need an endpoint that looked up the route from a redis server or something.

**Comment by nokome** [comment]
After some more thought, we should be able to avoid having to deploy and maintain Redis and instead take a stateless approach using JWT tokens and X-Accel-Redirect in `server.js`

**Comment by nokome** [comment]
In the interests of getting a deployment going, and because this seems fairly fundamental to the architecture, I'm going to make a start on this.

Also, I think it will deal with #7

**Comment by finlay** [comment]
Looking at the Kubernettes ingress system, which seems like the right way to do thing.

Looking at doing it with an nginx based system, and a JWT Token

**Comment by yoshuawuyts** [comment]
> JWT Token

Lil note from some research I did a while back: traditional JWT approaches are susceptible to downgrade attacks because they're multi-protocol. There's a few safer versions out there, but it's worth checking how it's done.

Alternatively there's Macaroons, which is a bit stronger and has some other cool characteristics. Amongst others this allows creating third tokens for access to specific resources without a central server involved for the issuing. This is cool to provide URLs to restricted resources that just work (as done in Google Drive when sharing a link to a file).

**Comment by nokome** [comment]
@yoshuawuyts : thanks for the pointer to macaroons! Given the time available, I suggest we stick with JWT for now and replace them with Macaroons later. I'll start a new issue for that.
