### ISSUE TITLE
Reimplement in ...

### ISSUE THREAD

**Issue by nokome** [stencila/sibyl#52]
The core `sibyl.sh` is written in Bash. Bash has several advantages for prototyping but it's not a great options as the feature set (and thus code base) expands. Reimplementation in another language should be fairly straight forward but we should ensure that whatever is used can be compiled into a standalone binary that can be executed at the command line like the bash script can.

Some option include:

- Node.js : can be compiled to binary using https://github.com/nexe/nexe
- Go : the implementation language for Docker and Kubernetes

Before reimplementing we shoud get high test coverage and do TDR (test driven reimplementation!).

**Comment by yoshuawuyts** [comment]
I'd personally be for the Node code, just because the rest of the project is already in JS - regardless of weighing off Go vs Node, I think having both Node __and__ Go is going to be more complex than choosing either (not only toolchain setup, but also knowledge of the language, etc.)

I think the biggest argument for Go would be smaller binaries - but disk space is cheap, and given we'll be downloading full OS images anyway, it probably doesn't matter too much.

**Comment by nokome** [comment]
Yep, I agree. The "Go is the implementation language of Docker and Kubernetes" argument is a bit of a red herring given that clients talk to the respective tool's socket API anyway.

**Comment by yoshuawuyts** [comment]
Oh by the way, think for a JS rewrite https://github.com/mafintosh/gunzip-maybe will come in real handy (:

**Comment by yoshuawuyts** [comment]
Resolution of this was that we're going to try reimplementing in JS using nexe - working on that today

**Comment by nokome** [comment]
Done!

**Comment by yoshuawuyts** [comment]
sweet! :D
